@startuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response


方耀辉 -> Bob: Another authentication Request
杨叶婷 <-- 方耀辉: another authentication Response
@enduml